before_script:
  - wget -nv https://common-lisp.net/project/cmucl/downloads/release/21a/cmucl-21a-x86-darwin.tar.bz2
  - tar xjf cmucl-21a-x86-darwin.tar.bz2
  - wget -nv https://common-lisp.net/project/cmucl/downloads/release/21a/cmucl-21a-x86-darwin.extra.tar.bz2
  - tar xjf cmucl-21a-x86-darwin.extra.tar.bz2
  - wget -nv http://beta.quicklisp.org/archive/rt/2010-10-06/rt-20101006-git.tgz
  - tar xzf rt-20101006-git.tgz

test:
  script:
    - ./run-tests
