before_script:
  - curl -s https://common-lisp.net/project/cmucl/downloads/snapshots/2016/01/cmucl-2016-01-x86-darwin.tar.bz2 | tar xf -
  - curl -s https://common-lisp.net/project/cmucl/downloads/snapshots/2016/01/cmucl-2016-01-x86-darwin.extra.tar.bz2 | tar xf -
  - curl -s http://beta.quicklisp.org/archive/rt/2010-10-06/rt-20101006-git.tgz | tar xf -

test:
  script:
    - ./run-tests
